### ISSUE TITLE
Any luck with persisting the directory stack?

### ISSUE THREAD

**Issue by devnoname120** [makp/term-configs#1]
I haven't yet found a way to do but it would be really helpful for me. Thanks.

**Edit**: looks like the [`dirpersist`](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/dirpersist) zsh plugin does the trick.

**Comment by makp** [comment]
Sorry I missed this. I know it has been a while but I've just added this plugin to my config. Thanks!
